language: python
python:
- '3.6'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAZRNPHKJIIFNOKDUD
  secret_access_key:
    secure: xZ4O+MhOschWqOTCFcMRW/uo+zV4dNE1Xov9Fn0VUtQlvqs63FqxwcMro/RJ4RzqHgdqWhiP4r7LjFHopfmM4ytWJzmq5TGxQraTFcetQe8cTKHM6iF6ikgVr9USt88RyOD9Jex/oyijG9t3BiGDmcZscU5RsAFhscqB96DHHb7A1IBxLZzU+Fc9Pwf4KfSieYCAtfw9MjOTxzm6cXe5mLEpx/auACCoifizHeGwPxtMg5dlYwGQNpCw14S9qLseYWP6wxx5XVK7y6e3niuD41uE0jhYgaKdG3WJvHWsarjCDYXcVp/FC1erQO79e6WSBDxIRMfRBogU24viyd2YQlWoZ2yjLGuuMys7R1/7us1lNoNYV1UUfMsqeg7QXkvlK4lexYVJjiGufFUPDfk6RUdtWyiAS1wet1ZAp8frnmfieRZYyNcjFh6eiwcsoN3buod5lYwio20FPWOReiXCN3DUmQPhXw2wxn0LNBrxPaTsNIA+Mlcq9HkmNyZfzQXxOeD1E4dYdpL/5a3AcUkvVj6eYHZQ50qBDKuho4zTXd/6mden29gBSKmQIVVXh6TU0tyrQeNhnIfN3dFe8RgZAnAaEFrS/HX0/9VPLL4c1s4atR4QpA24CbzjxaRc0jADhE6oBelvfPY30M2iVCMx8/mu8IciXQDlpemq5R7LGuQ=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: niaid-clinical-trials-dictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/niaid-clinical-trials-dictionary
    all_branches: true
